// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: internal/shared/pb/pm/password_manager.proto

package pm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry_EntryType int32

const (
	Entry_ENTRY_TYPE_UNSPECIFIED Entry_EntryType = 0
	Entry_ENTRY_TYPE_LOGIN       Entry_EntryType = 1
	Entry_ENTRY_TYPE_TEXT        Entry_EntryType = 2
	Entry_ENTRY_TYPE_BINARY      Entry_EntryType = 3
	Entry_ENTRY_TYPE_CARD        Entry_EntryType = 4
)

// Enum value maps for Entry_EntryType.
var (
	Entry_EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_LOGIN",
		2: "ENTRY_TYPE_TEXT",
		3: "ENTRY_TYPE_BINARY",
		4: "ENTRY_TYPE_CARD",
	}
	Entry_EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_LOGIN":       1,
		"ENTRY_TYPE_TEXT":        2,
		"ENTRY_TYPE_BINARY":      3,
		"ENTRY_TYPE_CARD":        4,
	}
)

func (x Entry_EntryType) Enum() *Entry_EntryType {
	p := new(Entry_EntryType)
	*p = x
	return p
}

func (x Entry_EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entry_EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_shared_pb_pm_password_manager_proto_enumTypes[0].Descriptor()
}

func (Entry_EntryType) Type() protoreflect.EnumType {
	return &file_internal_shared_pb_pm_password_manager_proto_enumTypes[0]
}

func (x Entry_EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ListEntriesRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tags []string               `protobuf:"bytes,1,rep,name=tags,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEntriesRequest) GetTags() []string {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *ListEntriesRequest) SetTags(v []string) {
	x.xxx_hidden_Tags = v
}

type ListEntriesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tags []string
}

func (b0 ListEntriesRequest_builder) Build() *ListEntriesRequest {
	m0 := &ListEntriesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tags = b.Tags
	return m0
}

type ListEntriesResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries    *[]*Entry              `protobuf:"bytes,1,rep,name=entries,proto3"`
	xxx_hidden_TotalCount int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *ListEntriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *ListEntriesResponse) SetEntries(v []*Entry) {
	x.xxx_hidden_Entries = &v
}

func (x *ListEntriesResponse) SetTotalCount(v int32) {
	x.xxx_hidden_TotalCount = v
}

type ListEntriesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries    []*Entry
	TotalCount int32
}

func (b0 ListEntriesResponse_builder) Build() *ListEntriesResponse {
	m0 := &ListEntriesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	x.xxx_hidden_TotalCount = b.TotalCount
	return m0
}

type CreateEntryRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateEntryRequest) GetEntry() *Entry {
	if x != nil {
		return x.xxx_hidden_Entry
	}
	return nil
}

func (x *CreateEntryRequest) SetEntry(v *Entry) {
	x.xxx_hidden_Entry = v
}

func (x *CreateEntryRequest) HasEntry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entry != nil
}

func (x *CreateEntryRequest) ClearEntry() {
	x.xxx_hidden_Entry = nil
}

type CreateEntryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry *Entry
}

func (b0 CreateEntryRequest_builder) Build() *CreateEntryRequest {
	m0 := &CreateEntryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = b.Entry
	return m0
}

type CreateEntryResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEntryResponse) Reset() {
	*x = CreateEntryResponse{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryResponse) ProtoMessage() {}

func (x *CreateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.xxx_hidden_Entry
	}
	return nil
}

func (x *CreateEntryResponse) SetEntry(v *Entry) {
	x.xxx_hidden_Entry = v
}

func (x *CreateEntryResponse) HasEntry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entry != nil
}

func (x *CreateEntryResponse) ClearEntry() {
	x.xxx_hidden_Entry = nil
}

type CreateEntryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry *Entry
}

func (b0 CreateEntryResponse_builder) Build() *CreateEntryResponse {
	m0 := &CreateEntryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = b.Entry
	return m0
}

type UpdateEntryRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEntryRequest) Reset() {
	*x = UpdateEntryRequest{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryRequest) ProtoMessage() {}

func (x *UpdateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateEntryRequest) GetEntry() *Entry {
	if x != nil {
		return x.xxx_hidden_Entry
	}
	return nil
}

func (x *UpdateEntryRequest) SetEntry(v *Entry) {
	x.xxx_hidden_Entry = v
}

func (x *UpdateEntryRequest) HasEntry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entry != nil
}

func (x *UpdateEntryRequest) ClearEntry() {
	x.xxx_hidden_Entry = nil
}

type UpdateEntryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry *Entry
}

func (b0 UpdateEntryRequest_builder) Build() *UpdateEntryRequest {
	m0 := &UpdateEntryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = b.Entry
	return m0
}

type UpdateEntryResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEntryResponse) Reset() {
	*x = UpdateEntryResponse{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryResponse) ProtoMessage() {}

func (x *UpdateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.xxx_hidden_Entry
	}
	return nil
}

func (x *UpdateEntryResponse) SetEntry(v *Entry) {
	x.xxx_hidden_Entry = v
}

func (x *UpdateEntryResponse) HasEntry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entry != nil
}

func (x *UpdateEntryResponse) ClearEntry() {
	x.xxx_hidden_Entry = nil
}

type UpdateEntryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry *Entry
}

func (b0 UpdateEntryResponse_builder) Build() *UpdateEntryResponse {
	m0 := &UpdateEntryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = b.Entry
	return m0
}

type DeleteEntryRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EntryId string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteEntryRequest) GetEntryId() string {
	if x != nil {
		return x.xxx_hidden_EntryId
	}
	return ""
}

func (x *DeleteEntryRequest) SetEntryId(v string) {
	x.xxx_hidden_EntryId = v
}

type DeleteEntryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EntryId string
}

func (b0 DeleteEntryRequest_builder) Build() *DeleteEntryRequest {
	m0 := &DeleteEntryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EntryId = b.EntryId
	return m0
}

type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteEntryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteEntryResponse_builder) Build() *DeleteEntryResponse {
	m0 := &DeleteEntryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetEntryRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EntryId string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetEntryRequest) GetEntryId() string {
	if x != nil {
		return x.xxx_hidden_EntryId
	}
	return ""
}

func (x *GetEntryRequest) SetEntryId(v string) {
	x.xxx_hidden_EntryId = v
}

type GetEntryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EntryId string
}

func (b0 GetEntryRequest_builder) Build() *GetEntryRequest {
	m0 := &GetEntryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EntryId = b.EntryId
	return m0
}

type GetEntryResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entry *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.xxx_hidden_Entry
	}
	return nil
}

func (x *GetEntryResponse) SetEntry(v *Entry) {
	x.xxx_hidden_Entry = v
}

func (x *GetEntryResponse) HasEntry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entry != nil
}

func (x *GetEntryResponse) ClearEntry() {
	x.xxx_hidden_Entry = nil
}

type GetEntryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entry *Entry
}

func (b0 GetEntryResponse_builder) Build() *GetEntryResponse {
	m0 := &GetEntryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entry = b.Entry
	return m0
}

type SyncRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Since *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return nil
}

func (x *SyncRequest) SetSince(v *timestamppb.Timestamp) {
	x.xxx_hidden_Since = v
}

func (x *SyncRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Since != nil
}

func (x *SyncRequest) ClearSince() {
	x.xxx_hidden_Since = nil
}

type SyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Since *timestamppb.Timestamp
}

func (b0 SyncRequest_builder) Build() *SyncRequest {
	m0 := &SyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Since = b.Since
	return m0
}

type SyncResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries         *[]*Entry              `protobuf:"bytes,1,rep,name=entries,proto3"`
	xxx_hidden_LastSync        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync,json=lastSync,proto3"`
	xxx_hidden_ReadOnly        bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3"`
	xxx_hidden_TotalCount      int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3"`
	xxx_hidden_DeletedEntryIds []string               `protobuf:"bytes,5,rep,name=deleted_entry_ids,json=deletedEntryIds,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncResponse) GetEntries() []*Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *SyncResponse) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSync
	}
	return nil
}

func (x *SyncResponse) GetReadOnly() bool {
	if x != nil {
		return x.xxx_hidden_ReadOnly
	}
	return false
}

func (x *SyncResponse) GetTotalCount() int32 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *SyncResponse) GetDeletedEntryIds() []string {
	if x != nil {
		return x.xxx_hidden_DeletedEntryIds
	}
	return nil
}

func (x *SyncResponse) SetEntries(v []*Entry) {
	x.xxx_hidden_Entries = &v
}

func (x *SyncResponse) SetLastSync(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastSync = v
}

func (x *SyncResponse) SetReadOnly(v bool) {
	x.xxx_hidden_ReadOnly = v
}

func (x *SyncResponse) SetTotalCount(v int32) {
	x.xxx_hidden_TotalCount = v
}

func (x *SyncResponse) SetDeletedEntryIds(v []string) {
	x.xxx_hidden_DeletedEntryIds = v
}

func (x *SyncResponse) HasLastSync() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSync != nil
}

func (x *SyncResponse) ClearLastSync() {
	x.xxx_hidden_LastSync = nil
}

type SyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries         []*Entry
	LastSync        *timestamppb.Timestamp
	ReadOnly        bool
	TotalCount      int32
	DeletedEntryIds []string
}

func (b0 SyncResponse_builder) Build() *SyncResponse {
	m0 := &SyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	x.xxx_hidden_LastSync = b.LastSync
	x.xxx_hidden_ReadOnly = b.ReadOnly
	x.xxx_hidden_TotalCount = b.TotalCount
	x.xxx_hidden_DeletedEntryIds = b.DeletedEntryIds
	return m0
}

type Entry struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Title         string                 `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Description   string                 `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3"`
	xxx_hidden_EntryType     Entry_EntryType        `protobuf:"varint,6,opt,name=entry_type,json=entryType,proto3,enum=pswmanager.Entry_EntryType"`
	xxx_hidden_Meta          *structpb.Struct       `protobuf:"bytes,7,opt,name=meta,proto3"`
	xxx_hidden_EncryptedBlob []byte                 `protobuf:"bytes,8,opt,name=encrypted_blob,json=encryptedBlob,proto3"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3"`
	xxx_hidden_ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3,oneof"`
	xxx_hidden_Version       uint32                 `protobuf:"varint,12,opt,name=version,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_pb_pm_password_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Entry) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *Entry) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *Entry) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *Entry) GetEntryType() Entry_EntryType {
	if x != nil {
		return x.xxx_hidden_EntryType
	}
	return Entry_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetMeta() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *Entry) GetEncryptedBlob() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedBlob
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Entry) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Entry) GetVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Entry) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Entry) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *Entry) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *Entry) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Entry) SetTags(v []string) {
	x.xxx_hidden_Tags = v
}

func (x *Entry) SetEntryType(v Entry_EntryType) {
	x.xxx_hidden_EntryType = v
}

func (x *Entry) SetMeta(v *structpb.Struct) {
	x.xxx_hidden_Meta = v
}

func (x *Entry) SetEncryptedBlob(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedBlob = v
}

func (x *Entry) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Entry) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Entry) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Entry) SetVersion(v uint32) {
	x.xxx_hidden_Version = v
}

func (x *Entry) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *Entry) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Entry) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Entry) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Entry) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *Entry) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Entry) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Entry) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            string
	UserId        string
	Title         string
	Description   string
	Tags          []string
	EntryType     Entry_EntryType
	Meta          *structpb.Struct
	EncryptedBlob []byte
	CreatedAt     *timestamppb.Timestamp
	UpdatedAt     *timestamppb.Timestamp
	ExpiresAt     *timestamppb.Timestamp
	Version       uint32
}

func (b0 Entry_builder) Build() *Entry {
	m0 := &Entry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Tags = b.Tags
	x.xxx_hidden_EntryType = b.EntryType
	x.xxx_hidden_Meta = b.Meta
	x.xxx_hidden_EncryptedBlob = b.EncryptedBlob
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	x.xxx_hidden_Version = b.Version
	return m0
}

var File_internal_shared_pb_pm_password_manager_proto protoreflect.FileDescriptor

const file_internal_shared_pb_pm_password_manager_proto_rawDesc = "" +
	"\n" +
	",internal/shared/pb/pm/password_manager.proto\x12\n" +
	"pswmanager\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"(\n" +
	"\x12ListEntriesRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"c\n" +
	"\x13ListEntriesResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.pswmanager.EntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"=\n" +
	"\x12CreateEntryRequest\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.pswmanager.EntryR\x05entry\">\n" +
	"\x13CreateEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.pswmanager.EntryR\x05entry\"=\n" +
	"\x12UpdateEntryRequest\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.pswmanager.EntryR\x05entry\">\n" +
	"\x13UpdateEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.pswmanager.EntryR\x05entry\"/\n" +
	"\x12DeleteEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"\x15\n" +
	"\x13DeleteEntryResponse\",\n" +
	"\x0fGetEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\";\n" +
	"\x10GetEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.pswmanager.EntryR\x05entry\"?\n" +
	"\vSyncRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\xde\x01\n" +
	"\fSyncResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.pswmanager.EntryR\aentries\x127\n" +
	"\tlast_sync\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12*\n" +
	"\x11deleted_entry_ids\x18\x05 \x03(\tR\x0fdeletedEntryIds\"\xeb\x04\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12:\n" +
	"\n" +
	"entry_type\x18\x06 \x01(\x0e2\x1b.pswmanager.Entry.EntryTypeR\tentryType\x12+\n" +
	"\x04meta\x18\a \x01(\v2\x17.google.protobuf.StructR\x04meta\x12%\n" +
	"\x0eencrypted_blob\x18\b \x01(\fR\rencryptedBlob\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\f \x01(\rR\aversion\"~\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTRY_TYPE_LOGIN\x10\x01\x12\x13\n" +
	"\x0fENTRY_TYPE_TEXT\x10\x02\x12\x15\n" +
	"\x11ENTRY_TYPE_BINARY\x10\x03\x12\x13\n" +
	"\x0fENTRY_TYPE_CARD\x10\x04B\r\n" +
	"\v_expires_at2\xda\x03\n" +
	"\x16PasswordManagerService\x129\n" +
	"\x04Sync\x12\x17.pswmanager.SyncRequest\x1a\x18.pswmanager.SyncResponse\x12N\n" +
	"\vListEntries\x12\x1e.pswmanager.ListEntriesRequest\x1a\x1f.pswmanager.ListEntriesResponse\x12E\n" +
	"\bGetEntry\x12\x1b.pswmanager.GetEntryRequest\x1a\x1c.pswmanager.GetEntryResponse\x12N\n" +
	"\vCreateEntry\x12\x1e.pswmanager.CreateEntryRequest\x1a\x1f.pswmanager.CreateEntryResponse\x12N\n" +
	"\vUpdateEntry\x12\x1e.pswmanager.UpdateEntryRequest\x1a\x1f.pswmanager.UpdateEntryResponse\x12N\n" +
	"\vDeleteEntry\x12\x1e.pswmanager.DeleteEntryRequest\x1a\x1f.pswmanager.DeleteEntryResponseB>Z<github.com/Schera-ole/password_manager/internal/shared/pb/pmb\x06proto3"

var file_internal_shared_pb_pm_password_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_shared_pb_pm_password_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_shared_pb_pm_password_manager_proto_goTypes = []any{
	(Entry_EntryType)(0),          // 0: pswmanager.Entry.EntryType
	(*ListEntriesRequest)(nil),    // 1: pswmanager.ListEntriesRequest
	(*ListEntriesResponse)(nil),   // 2: pswmanager.ListEntriesResponse
	(*CreateEntryRequest)(nil),    // 3: pswmanager.CreateEntryRequest
	(*CreateEntryResponse)(nil),   // 4: pswmanager.CreateEntryResponse
	(*UpdateEntryRequest)(nil),    // 5: pswmanager.UpdateEntryRequest
	(*UpdateEntryResponse)(nil),   // 6: pswmanager.UpdateEntryResponse
	(*DeleteEntryRequest)(nil),    // 7: pswmanager.DeleteEntryRequest
	(*DeleteEntryResponse)(nil),   // 8: pswmanager.DeleteEntryResponse
	(*GetEntryRequest)(nil),       // 9: pswmanager.GetEntryRequest
	(*GetEntryResponse)(nil),      // 10: pswmanager.GetEntryResponse
	(*SyncRequest)(nil),           // 11: pswmanager.SyncRequest
	(*SyncResponse)(nil),          // 12: pswmanager.SyncResponse
	(*Entry)(nil),                 // 13: pswmanager.Entry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 15: google.protobuf.Struct
}
var file_internal_shared_pb_pm_password_manager_proto_depIdxs = []int32{
	13, // 0: pswmanager.ListEntriesResponse.entries:type_name -> pswmanager.Entry
	13, // 1: pswmanager.CreateEntryRequest.entry:type_name -> pswmanager.Entry
	13, // 2: pswmanager.CreateEntryResponse.entry:type_name -> pswmanager.Entry
	13, // 3: pswmanager.UpdateEntryRequest.entry:type_name -> pswmanager.Entry
	13, // 4: pswmanager.UpdateEntryResponse.entry:type_name -> pswmanager.Entry
	13, // 5: pswmanager.GetEntryResponse.entry:type_name -> pswmanager.Entry
	14, // 6: pswmanager.SyncRequest.since:type_name -> google.protobuf.Timestamp
	13, // 7: pswmanager.SyncResponse.entries:type_name -> pswmanager.Entry
	14, // 8: pswmanager.SyncResponse.last_sync:type_name -> google.protobuf.Timestamp
	0,  // 9: pswmanager.Entry.entry_type:type_name -> pswmanager.Entry.EntryType
	15, // 10: pswmanager.Entry.meta:type_name -> google.protobuf.Struct
	14, // 11: pswmanager.Entry.created_at:type_name -> google.protobuf.Timestamp
	14, // 12: pswmanager.Entry.updated_at:type_name -> google.protobuf.Timestamp
	14, // 13: pswmanager.Entry.expires_at:type_name -> google.protobuf.Timestamp
	11, // 14: pswmanager.PasswordManagerService.Sync:input_type -> pswmanager.SyncRequest
	1,  // 15: pswmanager.PasswordManagerService.ListEntries:input_type -> pswmanager.ListEntriesRequest
	9,  // 16: pswmanager.PasswordManagerService.GetEntry:input_type -> pswmanager.GetEntryRequest
	3,  // 17: pswmanager.PasswordManagerService.CreateEntry:input_type -> pswmanager.CreateEntryRequest
	5,  // 18: pswmanager.PasswordManagerService.UpdateEntry:input_type -> pswmanager.UpdateEntryRequest
	7,  // 19: pswmanager.PasswordManagerService.DeleteEntry:input_type -> pswmanager.DeleteEntryRequest
	12, // 20: pswmanager.PasswordManagerService.Sync:output_type -> pswmanager.SyncResponse
	2,  // 21: pswmanager.PasswordManagerService.ListEntries:output_type -> pswmanager.ListEntriesResponse
	10, // 22: pswmanager.PasswordManagerService.GetEntry:output_type -> pswmanager.GetEntryResponse
	4,  // 23: pswmanager.PasswordManagerService.CreateEntry:output_type -> pswmanager.CreateEntryResponse
	6,  // 24: pswmanager.PasswordManagerService.UpdateEntry:output_type -> pswmanager.UpdateEntryResponse
	8,  // 25: pswmanager.PasswordManagerService.DeleteEntry:output_type -> pswmanager.DeleteEntryResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_shared_pb_pm_password_manager_proto_init() }
func file_internal_shared_pb_pm_password_manager_proto_init() {
	if File_internal_shared_pb_pm_password_manager_proto != nil {
		return
	}
	file_internal_shared_pb_pm_password_manager_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_shared_pb_pm_password_manager_proto_rawDesc), len(file_internal_shared_pb_pm_password_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_shared_pb_pm_password_manager_proto_goTypes,
		DependencyIndexes: file_internal_shared_pb_pm_password_manager_proto_depIdxs,
		EnumInfos:         file_internal_shared_pb_pm_password_manager_proto_enumTypes,
		MessageInfos:      file_internal_shared_pb_pm_password_manager_proto_msgTypes,
	}.Build()
	File_internal_shared_pb_pm_password_manager_proto = out.File
	file_internal_shared_pb_pm_password_manager_proto_goTypes = nil
	file_internal_shared_pb_pm_password_manager_proto_depIdxs = nil
}
