// Package define common models for client and server
package models

import (
	"time"
)

// Entry - encrypted user record
type Entry struct {
	ID            string    // UUID, generated by client
	UserID        string    // User email (unique identifier)
	Title         string    // Entry title/name
	Description   string    // Entry description
	Tags          []string  // Tags for filtering
	Type          EntryType // Data type: login, text, binary, card
	Meta          Meta      // Arbitrary key value
	EncryptedBlob []byte    // Encrypted data (includes IV)
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiresAt     *time.Time
	Version       int64 // for synchronization
}

type EntryType int

const (
	EntryTypeUnspecified EntryType = iota
	EntryTypeLogin
	EntryTypeText
	EntryTypeBinary
	EntryTypeCard
)

type Meta map[string]string

// SyncLog represents a log entry for synchronization
type SyncLog struct {
	ID        int64     // Auto-increment ID
	UserID    string    // User email
	EntryID   string    // Entry UUID
	Timestamp time.Time // When the change occurred
	Version   int64     // Entry version at the time of change
}

// User represents a registered user in the system
type User struct {
	Email        string // Unique email address
	PasswordHash string // Hashed password in format: base64(salt)$base64(hash)
	EncSalt      string // Encryption salt for client data (generated by server)
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
